apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
        app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"  
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 64Mi
  

